### ISSUE TITLE
Figure out a way to cut dependencies.

### ISSUE THREAD

**Issue by tarikeshaq** [tarikeshaq/update-notifier#20]
Currently the project pulls in [reqwest](https://crates.io/crates/reqwest) which pulls in tokio along with a ton of other dependencies which is unexpected for an update-notifier that should be lightweight. In other words, try to figure out how to send the requests **with something that is lighter than reqwest**.

**Comment by vladikoff** [comment]
Ref: https://users.rust-lang.org/t/lightweight-alternative-for-reqwest/33601/2

**Comment by tarikeshaq** [comment]
Was able to get it down to 95 crates from 126 by using [isahc](https://github.com/sagebind/isahc) Still feels like a lot
